# Server port
server.port=8086

# Application name
spring.application.name=notification-service

# MySQL Configuration (adjust if you are using different DB)
spring.datasource.url=jdbc:mysql://localhost:3306/hireconnect_notification
spring.datasource.username=root
spring.datasource.password=ckjain1166

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optional (good for consistent timestamps)
#spring.jackson.serialization.write-dates-as-timestamps=false
