server.port=8088

spring.application.name=analytics-service

# Upstream service URLs
services.job-url=http://localhost:8082
services.application-url=http://localhost:8084
services.interview-url=http://localhost:8085
services.profile-url=http://localhost:8083
